spring:
  redis:
    host: localhost
    port: 6379
    client-name: k-redis
  cache:
    type: redis
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
        - "*"