spring:
  redis:
    port: 26379
    sentinel:
      master: k_redis
      nodes:
        - localhost:16379
        - localhost:26379
        - localhost:36379
  cache:
    type: redis
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
        - "*"